### [actuator test] 어플리케이션를 셧다운 한다.
POST http://localhost:8080/actuator/shutdown
Content-Type: application/json

### [actuator test] OS 및 Java의 추가정보를 취득한다.
GET http://localhost:8080/actuator/info

### [actuator test] 새로운 상품을 등록한다.
POST http://localhost:8080/v1/orders/addProduct
Content-Type: application/json

{
  "id" :  "a00001",
  "quantity" : 10,
  "price" : 23000,
  "productName": "순무신발"
}

### [actuator test] 새로운 상품을 등록한다.
POST http://localhost:8080/v1/orders/addProduct
Content-Type: application/json

{
  "id" :  "a00002",
  "quantity" : 5,
  "price" : 33000,
  "productName": "순무신발"
}

### [actuator test] 새로운 상품을 등록한다.
POST http://localhost:8080/v1/orders/addProduct
Content-Type: application/json

{
  "id" :  "a00003",
  "quantity" : 2,
  "price" : 2000,
  "productName": "순무양말"
}

### [actuator test] 주문의 내용을 갱신한다.
POST http://localhost:8080/v1/orders/updateProduct
Content-Type: application/json

{
  "id" :  "a00001",
  "quantity" : 5,
  "price" : 23000,
  "productName": "순무신발2"
}

### [actuator test] 상품을 검색한다.
GET http://localhost:8080/v1/orders/products/a00001

### [actuator test] 상품명을 검색한다.
GET http://localhost:8080/v1/orders/products/name/순무신발


### [actuator Redis template test] 손 장갑을 등록한다.
POST http://localhost:8080/v2/orders/addProduct
Content-Type: application/json

{
  "id" :  "b00001",
  "quantity" : 5,
  "price" : 13000,
  "productName": "순무장갑"
}

### [actuator Redis template test] 손 장갑을 등록한다.
POST http://localhost:8080/v2/orders/addProduct
Content-Type: application/json

{
  "id" :  "b00002",
  "quantity" : 3,
  "price" : 1000,
  "productName": "순무장갑"
}

### [actuator Redis template test] 장갑명을 수정한다.
POST http://localhost:8080/v2/orders/updateProduct
Content-Type: application/json

{
  "id" :  "b00002",
  "quantity" : 3,
  "price" : 1000,
  "productName": "빨강순무장갑"
}

###[actuator Redis template test] 손 장갑을 ID로 검색한다.
GET http://localhost:8080/v2/orders/products/b00001


###[actuator Redis template test] 손 장갑을 이름으로 검색한다.
GET http://localhost:8080/v2/orders/products/name/순무장갑