management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true

logging:
  level:
    kr.pe.yoonsm.actuator: debug

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true