management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true

logging:
  level:
    kr.pe.yoonsm.actuator: debug

spring:
  cache:
    redis:
      host: localhost
      port: 6379
      time-to-live: 3600